<?php
/**
 * This file was generated by Atlas. Changes will be overwritten.
 */
declare(strict_types=1);

namespace Circli\Database\Tests\Atlas\DataSource\People;

use Atlas\Table\Row;

/**
 * @property mixed $id INTEGER
 * @property mixed $name TEXT NOT NULL
 */
class PeopleRow extends Row
{
    protected $cols = [
        'id' => null,
        'name' => null,
    ];
}
