<?php
/**
 * This file was generated by Atlas. Changes will be overwritten.
 */
declare(strict_types=1);

namespace Circli\Database\Tests\Atlas\DataSource\People;

/**
 * @property mixed $id INTEGER
 * @property mixed $name TEXT NOT NULL
 */
trait PeopleFields
{
}
