<?php
/**
 * This file was generated by Atlas. Changes will be overwritten.
 */
declare(strict_types=1);

namespace Circli\Database\Tests\Atlas\DataSource\People;

use Atlas\Table\Table;

/**
 * @method PeopleRow|null fetchRow($primaryVal)
 * @method PeopleRow[] fetchRows(array $primaryVals)
 * @method PeopleTableSelect select(array $whereEquals = [])
 * @method PeopleRow newRow(array $cols = [])
 * @method PeopleRow newSelectedRow(array $cols)
 */
class PeopleTable extends Table
{
    const DRIVER = 'sqlite';

    const NAME = 'people';

    const COLUMNS = [
        'id' => [
            'name' => 'id',
            'type' => 'INTEGER',
            'size' => null,
            'scale' => null,
            'notnull' => false,
            'default' => null,
            'autoinc' => true,
            'primary' => true,
            'options' => null,
        ],
        'name' => [
            'name' => 'name',
            'type' => 'TEXT',
            'size' => null,
            'scale' => null,
            'notnull' => true,
            'default' => null,
            'autoinc' => false,
            'primary' => false,
            'options' => null,
        ],
    ];

    const COLUMN_NAMES = [
        'id',
        'name',
    ];

    const COLUMN_DEFAULTS = [
        'id' => null,
        'name' => null,
    ];

    const PRIMARY_KEY = [
        'id',
    ];

    const AUTOINC_COLUMN = 'id';

    const AUTOINC_SEQUENCE = null;
}
